# Tzstats/Blockwatch Infrastructure
#
# Services/Containers
#  - tzstats
#
# Published Ports
#  - 8000  served fileserver
#
# Start with
# docker-compose up -d
#
version: '2.2'

services:
  tzstats:
    image: blockwatch-cc/tzstats:latest
    environment:
      TZSTATS_API_URL: https://api.tzstats.com
      SV_HEADERS_Content-Security-Policy: >
        default-src 'self';
        script-src 'self' 'unsafe-inline' https://www.google-analytics.com;
        style-src 'self' 'unsafe-inline';
        font-src 'self';
        img-src 'self' data: blob: https://*.tzstats.com https://www.google-analytics.com https://stats.g.doubleclick.net;
        media-src data: filesystem: mediastream: blob: https://*.tzstats.com;
        connect-src 'self' https://*.tzstats.com;
        worker-src 'self' blob:;
        child-src 'self' blob:;
        frame-src 'self' https://*.tzstats.com;
        frame-ancestors 'none';
        object-src 'none';
        form-action 'self' https://*.tzstats.com;
        report-uri /csplog;
    mem_limit: 64M
